[package]
name = "board"
version = "0.1.0"
authors = ["Andy Kurnia"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 3

[dependencies]
csv = "1"
rand = "0.7"
rand_chacha = "0.2.2"
rustyline = "7.1.0"
rustyline-derive = "0.4.0"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
shell-words = "1.0.0"
